<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
                {{ $report->name }}
            </h2>
            <div class="flex gap-2">
                @if($report->isCompleted())
                    <a href="{{ route('admin.reports.download', $report) }}" class="btn btn-primary">
                        Download Report
                    </a>
                @endif
                <a href="{{ route('admin.reports.index') }}" class="btn btn-secondary">
                    Back to Reports
                </a>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <!-- Report Details -->
                    <div class="grid grid-cols-2 gap-6 mb-6">
                        <div>
                            <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Report Type</h3>
                            <p class="mt-1 text-lg text-gray-900 dark:text-white">
                                {{ ucwords(str_replace('_', ' ', $report->report_type)) }}
                            </p>
                        </div>
                        <div>
                            <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Status</h3>
                            <p class="mt-1">
                                @if($report->status === 'completed')
                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                        Completed
                                    </span>
                                @elseif($report->status === 'pending')
                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">
                                        Pending
                                    </span>
                                @else
                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                        Failed
                                    </span>
                                @endif
                            </p>
                        </div>
                        <div>
                            <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Generated By</h3>
                            <p class="mt-1 text-lg text-gray-900 dark:text-white">
                                {{ $report->generatedBy->name }}
                            </p>
                        </div>
                        <div>
                            <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Generated At</h3>
                            <p class="mt-1 text-lg text-gray-900 dark:text-white">
                                {{ $report->generated_at?->format('M d, Y H:i') ?? 'N/A' }}
                            </p>
                        </div>
                        <div>
                            <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Format</h3>
                            <p class="mt-1 text-lg text-gray-900 dark:text-white">
                                {{ strtoupper($report->file_format) }}
                            </p>
                        </div>
                        @if($report->isScheduled())
                            <div>
                                <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Schedule</h3>
                                <p class="mt-1 text-lg text-gray-900 dark:text-white">
                                    {{ ucfirst($report->schedule_config['frequency'] ?? 'N/A') }}
                                </p>
                            </div>
                        @endif
                    </div>

                    @if($report->description)
                        <div class="mb-6">
                            <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Description</h3>
                            <p class="mt-1 text-gray-900 dark:text-white">
                                {{ $report->description }}
                            </p>
                        </div>
                    @endif

                    <!-- Parameters -->
                    @if($report->parameters)
                        <div class="mb-6">
                            <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Parameters</h3>
                            <div class="bg-gray-50 dark:bg-gray-900 rounded-lg p-4">
                                <dl class="grid grid-cols-2 gap-4">
                                    @foreach($report->parameters as $key => $value)
                                        @if($value)
                                            <div>
                                                <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">
                                                    {{ ucwords(str_replace('_', ' ', $key)) }}
                                                </dt>
                                                <dd class="mt-1 text-sm text-gray-900 dark:text-white">
                                                    {{ is_array($value) ? json_encode($value) : $value }}
                                                </dd>
                                            </div>
                                        @endif
                                    @endforeach
                                </dl>
                            </div>
                        </div>
                    @endif

                    <!-- Actions -->
                    <div class="flex justify-end gap-4 pt-6 border-t border-gray-200 dark:border-gray-700">
                        @if($report->isCompleted())
                            <a href="{{ route('admin.reports.download', $report) }}" class="btn btn-primary">
                                <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                </svg>
                                Download
                            </a>
                        @endif
                        <form method="POST" action="{{ route('admin.reports.destroy', $report) }}" class="inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this report?')">
                                Delete Report
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
