[program:lms-horizon]
process_name=%(program_name)s
command=php /var/www/lms/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/lms/storage/logs/horizon.log
stopwaitsecs=3600
startsecs=0
